version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: foko
      MYSQL_PASSWORD: foko
      MYSQL_ROOT_PASSWORD: foko
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306